// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/library/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/project/library/internal/entity"
)

// MockAuthorUseCase is a mock of AuthorUseCase interface.
type MockAuthorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorUseCaseMockRecorder
}

// MockAuthorUseCaseMockRecorder is the mock recorder for MockAuthorUseCase.
type MockAuthorUseCaseMockRecorder struct {
	mock *MockAuthorUseCase
}

// NewMockAuthorUseCase creates a new mock instance.
func NewMockAuthorUseCase(ctrl *gomock.Controller) *MockAuthorUseCase {
	mock := &MockAuthorUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorUseCase) EXPECT() *MockAuthorUseCaseMockRecorder {
	return m.recorder
}

// ChangeAuthor mocks base method.
func (m *MockAuthorUseCase) ChangeAuthor(ctx context.Context, authorID, authorName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeAuthor", ctx, authorID, authorName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeAuthor indicates an expected call of ChangeAuthor.
func (mr *MockAuthorUseCaseMockRecorder) ChangeAuthor(ctx, authorID, authorName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeAuthor", reflect.TypeOf((*MockAuthorUseCase)(nil).ChangeAuthor), ctx, authorID, authorName)
}

// GetAuthor mocks base method.
func (m *MockAuthorUseCase) GetAuthor(ctx context.Context, authorID string) (entity.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthor", ctx, authorID)
	ret0, _ := ret[0].(entity.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthor indicates an expected call of GetAuthor.
func (mr *MockAuthorUseCaseMockRecorder) GetAuthor(ctx, authorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthor", reflect.TypeOf((*MockAuthorUseCase)(nil).GetAuthor), ctx, authorID)
}

// RegisterAuthor mocks base method.
func (m *MockAuthorUseCase) RegisterAuthor(ctx context.Context, authorName string) (entity.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAuthor", ctx, authorName)
	ret0, _ := ret[0].(entity.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterAuthor indicates an expected call of RegisterAuthor.
func (mr *MockAuthorUseCaseMockRecorder) RegisterAuthor(ctx, authorName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAuthor", reflect.TypeOf((*MockAuthorUseCase)(nil).RegisterAuthor), ctx, authorName)
}

// MockBooksUseCase is a mock of BooksUseCase interface.
type MockBooksUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBooksUseCaseMockRecorder
}

// MockBooksUseCaseMockRecorder is the mock recorder for MockBooksUseCase.
type MockBooksUseCaseMockRecorder struct {
	mock *MockBooksUseCase
}

// NewMockBooksUseCase creates a new mock instance.
func NewMockBooksUseCase(ctrl *gomock.Controller) *MockBooksUseCase {
	mock := &MockBooksUseCase{ctrl: ctrl}
	mock.recorder = &MockBooksUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBooksUseCase) EXPECT() *MockBooksUseCaseMockRecorder {
	return m.recorder
}

// GetAuthorBooks mocks base method.
func (m *MockBooksUseCase) GetAuthorBooks(ctx context.Context, authorID string) ([]entity.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorBooks", ctx, authorID)
	ret0, _ := ret[0].([]entity.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorBooks indicates an expected call of GetAuthorBooks.
func (mr *MockBooksUseCaseMockRecorder) GetAuthorBooks(ctx, authorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorBooks", reflect.TypeOf((*MockBooksUseCase)(nil).GetAuthorBooks), ctx, authorID)
}

// GetBook mocks base method.
func (m *MockBooksUseCase) GetBook(ctx context.Context, bookID string) (entity.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBook", ctx, bookID)
	ret0, _ := ret[0].(entity.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBook indicates an expected call of GetBook.
func (mr *MockBooksUseCaseMockRecorder) GetBook(ctx, bookID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBook", reflect.TypeOf((*MockBooksUseCase)(nil).GetBook), ctx, bookID)
}

// RegisterBook mocks base method.
func (m *MockBooksUseCase) RegisterBook(ctx context.Context, book entity.Book) (entity.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterBook", ctx, book)
	ret0, _ := ret[0].(entity.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterBook indicates an expected call of RegisterBook.
func (mr *MockBooksUseCaseMockRecorder) RegisterBook(ctx, book interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterBook", reflect.TypeOf((*MockBooksUseCase)(nil).RegisterBook), ctx, book)
}

// UpdateBook mocks base method.
func (m *MockBooksUseCase) UpdateBook(ctx context.Context, bookID, name string, authorIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", ctx, bookID, name, authorIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockBooksUseCaseMockRecorder) UpdateBook(ctx, bookID, name, authorIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockBooksUseCase)(nil).UpdateBook), ctx, bookID, name, authorIDs)
}
