// Code generated by MockGen. DO NOT EDIT.
// Source: generated/api/library/library_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	library "github.com/project/library/generated/api/library"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockLibraryClient is a mock of LibraryClient interface.
type MockLibraryClient struct {
	ctrl     *gomock.Controller
	recorder *MockLibraryClientMockRecorder
}

// MockLibraryClientMockRecorder is the mock recorder for MockLibraryClient.
type MockLibraryClientMockRecorder struct {
	mock *MockLibraryClient
}

// NewMockLibraryClient creates a new mock instance.
func NewMockLibraryClient(ctrl *gomock.Controller) *MockLibraryClient {
	mock := &MockLibraryClient{ctrl: ctrl}
	mock.recorder = &MockLibraryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibraryClient) EXPECT() *MockLibraryClientMockRecorder {
	return m.recorder
}

// AddBook mocks base method.
func (m *MockLibraryClient) AddBook(ctx context.Context, in *library.AddBookRequest, opts ...grpc.CallOption) (*library.AddBookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBook", varargs...)
	ret0, _ := ret[0].(*library.AddBookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBook indicates an expected call of AddBook.
func (mr *MockLibraryClientMockRecorder) AddBook(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBook", reflect.TypeOf((*MockLibraryClient)(nil).AddBook), varargs...)
}

// ChangeAuthorInfo mocks base method.
func (m *MockLibraryClient) ChangeAuthorInfo(ctx context.Context, in *library.ChangeAuthorInfoRequest, opts ...grpc.CallOption) (*library.ChangeAuthorInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangeAuthorInfo", varargs...)
	ret0, _ := ret[0].(*library.ChangeAuthorInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeAuthorInfo indicates an expected call of ChangeAuthorInfo.
func (mr *MockLibraryClientMockRecorder) ChangeAuthorInfo(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeAuthorInfo", reflect.TypeOf((*MockLibraryClient)(nil).ChangeAuthorInfo), varargs...)
}

// GetAuthorBooks mocks base method.
func (m *MockLibraryClient) GetAuthorBooks(ctx context.Context, in *library.GetAuthorBooksRequest, opts ...grpc.CallOption) (library.Library_GetAuthorBooksClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAuthorBooks", varargs...)
	ret0, _ := ret[0].(library.Library_GetAuthorBooksClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorBooks indicates an expected call of GetAuthorBooks.
func (mr *MockLibraryClientMockRecorder) GetAuthorBooks(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorBooks", reflect.TypeOf((*MockLibraryClient)(nil).GetAuthorBooks), varargs...)
}

// GetAuthorInfo mocks base method.
func (m *MockLibraryClient) GetAuthorInfo(ctx context.Context, in *library.GetAuthorInfoRequest, opts ...grpc.CallOption) (*library.GetAuthorInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAuthorInfo", varargs...)
	ret0, _ := ret[0].(*library.GetAuthorInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorInfo indicates an expected call of GetAuthorInfo.
func (mr *MockLibraryClientMockRecorder) GetAuthorInfo(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorInfo", reflect.TypeOf((*MockLibraryClient)(nil).GetAuthorInfo), varargs...)
}

// GetBookInfo mocks base method.
func (m *MockLibraryClient) GetBookInfo(ctx context.Context, in *library.GetBookInfoRequest, opts ...grpc.CallOption) (*library.GetBookInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBookInfo", varargs...)
	ret0, _ := ret[0].(*library.GetBookInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookInfo indicates an expected call of GetBookInfo.
func (mr *MockLibraryClientMockRecorder) GetBookInfo(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookInfo", reflect.TypeOf((*MockLibraryClient)(nil).GetBookInfo), varargs...)
}

// RegisterAuthor mocks base method.
func (m *MockLibraryClient) RegisterAuthor(ctx context.Context, in *library.RegisterAuthorRequest, opts ...grpc.CallOption) (*library.RegisterAuthorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterAuthor", varargs...)
	ret0, _ := ret[0].(*library.RegisterAuthorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterAuthor indicates an expected call of RegisterAuthor.
func (mr *MockLibraryClientMockRecorder) RegisterAuthor(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAuthor", reflect.TypeOf((*MockLibraryClient)(nil).RegisterAuthor), varargs...)
}

// UpdateBook mocks base method.
func (m *MockLibraryClient) UpdateBook(ctx context.Context, in *library.UpdateBookRequest, opts ...grpc.CallOption) (*library.UpdateBookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBook", varargs...)
	ret0, _ := ret[0].(*library.UpdateBookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockLibraryClientMockRecorder) UpdateBook(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockLibraryClient)(nil).UpdateBook), varargs...)
}

// MockLibrary_GetAuthorBooksClient is a mock of Library_GetAuthorBooksClient interface.
type MockLibrary_GetAuthorBooksClient struct {
	ctrl     *gomock.Controller
	recorder *MockLibrary_GetAuthorBooksClientMockRecorder
}

// MockLibrary_GetAuthorBooksClientMockRecorder is the mock recorder for MockLibrary_GetAuthorBooksClient.
type MockLibrary_GetAuthorBooksClientMockRecorder struct {
	mock *MockLibrary_GetAuthorBooksClient
}

// NewMockLibrary_GetAuthorBooksClient creates a new mock instance.
func NewMockLibrary_GetAuthorBooksClient(ctrl *gomock.Controller) *MockLibrary_GetAuthorBooksClient {
	mock := &MockLibrary_GetAuthorBooksClient{ctrl: ctrl}
	mock.recorder = &MockLibrary_GetAuthorBooksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibrary_GetAuthorBooksClient) EXPECT() *MockLibrary_GetAuthorBooksClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockLibrary_GetAuthorBooksClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockLibrary_GetAuthorBooksClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockLibrary_GetAuthorBooksClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockLibrary_GetAuthorBooksClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockLibrary_GetAuthorBooksClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockLibrary_GetAuthorBooksClient)(nil).Context))
}

// Header mocks base method.
func (m *MockLibrary_GetAuthorBooksClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockLibrary_GetAuthorBooksClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockLibrary_GetAuthorBooksClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockLibrary_GetAuthorBooksClient) Recv() (*library.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*library.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockLibrary_GetAuthorBooksClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockLibrary_GetAuthorBooksClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockLibrary_GetAuthorBooksClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockLibrary_GetAuthorBooksClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockLibrary_GetAuthorBooksClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockLibrary_GetAuthorBooksClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockLibrary_GetAuthorBooksClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockLibrary_GetAuthorBooksClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockLibrary_GetAuthorBooksClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockLibrary_GetAuthorBooksClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockLibrary_GetAuthorBooksClient)(nil).Trailer))
}

// MockLibraryServer is a mock of LibraryServer interface.
type MockLibraryServer struct {
	ctrl     *gomock.Controller
	recorder *MockLibraryServerMockRecorder
}

// MockLibraryServerMockRecorder is the mock recorder for MockLibraryServer.
type MockLibraryServerMockRecorder struct {
	mock *MockLibraryServer
}

// NewMockLibraryServer creates a new mock instance.
func NewMockLibraryServer(ctrl *gomock.Controller) *MockLibraryServer {
	mock := &MockLibraryServer{ctrl: ctrl}
	mock.recorder = &MockLibraryServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibraryServer) EXPECT() *MockLibraryServerMockRecorder {
	return m.recorder
}

// AddBook mocks base method.
func (m *MockLibraryServer) AddBook(arg0 context.Context, arg1 *library.AddBookRequest) (*library.AddBookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBook", arg0, arg1)
	ret0, _ := ret[0].(*library.AddBookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBook indicates an expected call of AddBook.
func (mr *MockLibraryServerMockRecorder) AddBook(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBook", reflect.TypeOf((*MockLibraryServer)(nil).AddBook), arg0, arg1)
}

// ChangeAuthorInfo mocks base method.
func (m *MockLibraryServer) ChangeAuthorInfo(arg0 context.Context, arg1 *library.ChangeAuthorInfoRequest) (*library.ChangeAuthorInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeAuthorInfo", arg0, arg1)
	ret0, _ := ret[0].(*library.ChangeAuthorInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeAuthorInfo indicates an expected call of ChangeAuthorInfo.
func (mr *MockLibraryServerMockRecorder) ChangeAuthorInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeAuthorInfo", reflect.TypeOf((*MockLibraryServer)(nil).ChangeAuthorInfo), arg0, arg1)
}

// GetAuthorBooks mocks base method.
func (m *MockLibraryServer) GetAuthorBooks(arg0 *library.GetAuthorBooksRequest, arg1 library.Library_GetAuthorBooksServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorBooks", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAuthorBooks indicates an expected call of GetAuthorBooks.
func (mr *MockLibraryServerMockRecorder) GetAuthorBooks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorBooks", reflect.TypeOf((*MockLibraryServer)(nil).GetAuthorBooks), arg0, arg1)
}

// GetAuthorInfo mocks base method.
func (m *MockLibraryServer) GetAuthorInfo(arg0 context.Context, arg1 *library.GetAuthorInfoRequest) (*library.GetAuthorInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorInfo", arg0, arg1)
	ret0, _ := ret[0].(*library.GetAuthorInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorInfo indicates an expected call of GetAuthorInfo.
func (mr *MockLibraryServerMockRecorder) GetAuthorInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorInfo", reflect.TypeOf((*MockLibraryServer)(nil).GetAuthorInfo), arg0, arg1)
}

// GetBookInfo mocks base method.
func (m *MockLibraryServer) GetBookInfo(arg0 context.Context, arg1 *library.GetBookInfoRequest) (*library.GetBookInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookInfo", arg0, arg1)
	ret0, _ := ret[0].(*library.GetBookInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookInfo indicates an expected call of GetBookInfo.
func (mr *MockLibraryServerMockRecorder) GetBookInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookInfo", reflect.TypeOf((*MockLibraryServer)(nil).GetBookInfo), arg0, arg1)
}

// RegisterAuthor mocks base method.
func (m *MockLibraryServer) RegisterAuthor(arg0 context.Context, arg1 *library.RegisterAuthorRequest) (*library.RegisterAuthorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAuthor", arg0, arg1)
	ret0, _ := ret[0].(*library.RegisterAuthorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterAuthor indicates an expected call of RegisterAuthor.
func (mr *MockLibraryServerMockRecorder) RegisterAuthor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAuthor", reflect.TypeOf((*MockLibraryServer)(nil).RegisterAuthor), arg0, arg1)
}

// UpdateBook mocks base method.
func (m *MockLibraryServer) UpdateBook(arg0 context.Context, arg1 *library.UpdateBookRequest) (*library.UpdateBookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", arg0, arg1)
	ret0, _ := ret[0].(*library.UpdateBookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockLibraryServerMockRecorder) UpdateBook(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockLibraryServer)(nil).UpdateBook), arg0, arg1)
}

// MockUnsafeLibraryServer is a mock of UnsafeLibraryServer interface.
type MockUnsafeLibraryServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeLibraryServerMockRecorder
}

// MockUnsafeLibraryServerMockRecorder is the mock recorder for MockUnsafeLibraryServer.
type MockUnsafeLibraryServerMockRecorder struct {
	mock *MockUnsafeLibraryServer
}

// NewMockUnsafeLibraryServer creates a new mock instance.
func NewMockUnsafeLibraryServer(ctrl *gomock.Controller) *MockUnsafeLibraryServer {
	mock := &MockUnsafeLibraryServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeLibraryServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeLibraryServer) EXPECT() *MockUnsafeLibraryServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedLibraryServer mocks base method.
func (m *MockUnsafeLibraryServer) mustEmbedUnimplementedLibraryServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedLibraryServer")
}

// mustEmbedUnimplementedLibraryServer indicates an expected call of mustEmbedUnimplementedLibraryServer.
func (mr *MockUnsafeLibraryServerMockRecorder) mustEmbedUnimplementedLibraryServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedLibraryServer", reflect.TypeOf((*MockUnsafeLibraryServer)(nil).mustEmbedUnimplementedLibraryServer))
}

// MockLibrary_GetAuthorBooksServer is a mock of Library_GetAuthorBooksServer interface.
type MockLibrary_GetAuthorBooksServer struct {
	ctrl     *gomock.Controller
	recorder *MockLibrary_GetAuthorBooksServerMockRecorder
}

// MockLibrary_GetAuthorBooksServerMockRecorder is the mock recorder for MockLibrary_GetAuthorBooksServer.
type MockLibrary_GetAuthorBooksServerMockRecorder struct {
	mock *MockLibrary_GetAuthorBooksServer
}

// NewMockLibrary_GetAuthorBooksServer creates a new mock instance.
func NewMockLibrary_GetAuthorBooksServer(ctrl *gomock.Controller) *MockLibrary_GetAuthorBooksServer {
	mock := &MockLibrary_GetAuthorBooksServer{ctrl: ctrl}
	mock.recorder = &MockLibrary_GetAuthorBooksServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibrary_GetAuthorBooksServer) EXPECT() *MockLibrary_GetAuthorBooksServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockLibrary_GetAuthorBooksServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockLibrary_GetAuthorBooksServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockLibrary_GetAuthorBooksServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockLibrary_GetAuthorBooksServer) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockLibrary_GetAuthorBooksServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockLibrary_GetAuthorBooksServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockLibrary_GetAuthorBooksServer) Send(arg0 *library.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockLibrary_GetAuthorBooksServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockLibrary_GetAuthorBooksServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockLibrary_GetAuthorBooksServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockLibrary_GetAuthorBooksServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockLibrary_GetAuthorBooksServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockLibrary_GetAuthorBooksServer) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockLibrary_GetAuthorBooksServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockLibrary_GetAuthorBooksServer)(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockLibrary_GetAuthorBooksServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockLibrary_GetAuthorBooksServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockLibrary_GetAuthorBooksServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockLibrary_GetAuthorBooksServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockLibrary_GetAuthorBooksServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockLibrary_GetAuthorBooksServer)(nil).SetTrailer), arg0)
}
